# Prepare :: aws iam > create user: kaniko
---
apiVersion: v1
kind: Secret
metadata:
  name: aws-secret
  namespace: jenkins
type: Opaque
stringData:
  credentials: |
    [default]
    aws_access_key_id="{your-access-key}"
    aws_secret_access_key="{aws-secret-access-key}"
    aws_region=ap-northeast-2
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: docker-config
  namespace: jenkins
data:
  config.json: |
    { "credsStore": "ecr-login" }
