apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: boomb-developer-role
  namespace: boomb
rules:
  - apiGroups: [""]
    resources:
      - "pods"
      - "pods/attach"
      - "pods/exec"
      - "pods/log"
      - "services"
      - "serviceaccounts"
      - "persistentvolumes"
      - "persistentvolumeclaims"
      - "secrets"
      - "configmaps"
    verbs: ["get", "list", "watch", "create", "update"]

  - apiGroups: ["apps"]
    resources:
      - "deployments"
      - "statefulsets"
    verbs: ["get", "list", "watch", "create", "update", "patch"]

  - apiGroups: ["apps"]
    resources:
      - "daemonsets"
      - "replicasets"
    verbs: ["get", "list", "watch"]

  - apiGroups: ["networking.k8s.io", "storage.k8s.io"]
    resources:
      - "*"
    verbs: ["get", "list", "watch"]
