kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: aionu-operator-role-binding
  namespace: aion-u
roleRef:
  kind: Role
  name: boomb-developer-role
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: Group
    name: boomb-operator
    apiGroup: rbac.authorization.k8s.io
