apiVersion: v1
kind: PersistentVolume
metadata:
  name: s3-pv
spec:
  capacity:
    storage: 500Gi
  accessModes:
    - ReadWriteMany
  mountOptions:
    - allow-delete
  csi:
    driver: s3.csi.aws.com
    volumeHandle: s3-csi-driver-volume
    volumeAttributes:
      bucketName: aionu-test-bucket
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: s3-mlops-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 500Gi
  volumeName: s3-pv
---
apiVersion: v1
kind: Pod
metadata:
  name: s3-app
spec:
  containers:
    - name: app
      image: centos
      command: ["/bin/sh"]
      args:
        [
          "-c",
          "echo 'Hello from the container!' >> /data/$(date -u).txt; tail -f /dev/null",
        ]
      volumeMounts:
        - name: persistent-storage
          mountPath: /yuchan
  volumes:
    - name: persistent-storage
      persistentVolumeClaim:
        claimName: s3-mlops-pvc
