affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
        - matchExpressions:
            - key: karpenter.sh/nodepool
              operator: DoesNotExist
            - key: node-priority
              operator: In
              values:
                - ${eks_node_priority}

  podAntiAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
            - key: app.kubernetes.io/name
              operator: In
              values:
                - ${app_name}
        topologyKey: kubernetes.io/hostname

  podAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        podAffinityTerm:
          labelSelector:
            matchExpressions:
              - key: app.kubernetes.io/name
                operator: In
                values:
                  - ${app_name}
          topologyKey: topology.kubernetes.io/zone

tolerations:
  - key: app-priority
    operator: Equal
    value: ${eks_node_priority}
    effect: NoSchedule
